#!/bin/bash

if [ $# -lt 3 ]
then
  echo 'Arity error' >&2
  echo '  insert-file-to-file src target line-number [no-of-deletion=0]' >&2
  exit 1
fi

SRC=$1
TARGET=$2
LINE_NUMBER=$3
NO_OF_DELETION=$4
if [ -z $NO_OF_DELETION ]
then
  NO_OF_DELETION=0
fi

TEMPFILE=/tmp/tempfile-`date +%Y%m%d%H%M%S`
head -$((${LINE_NUMBER}-1)) $TARGET > $TEMPFILE
cat $SRC >> $TEMPFILE
tail -n +$(($LINE_NUMBER+$NO_OF_DELETION)) $TARGET >> $TEMPFILE
mv $TEMPFILE $TARGET
